### ISSUE TITLE
DNS record needs to be set

### ISSUE THREAD

**Issue by Dirk--** [OpenNauticalChart/wiki#1]

**Comment by OlafHannemann** [comment]
I will take care in the next few days

**Comment by OlafHannemann** [comment]
@Dirk-- The sub domain is created and the DNS record set. At the moment I get an 404 while opening it. Is on my or on your side? Can you do a quick check?

**Comment by Dirk--** [comment]
did you set A records?
62.138.1.116 > wiki.opennauticalchart.org
62.138.1.116 > forum.opennauticalchart.org
I can not see any at NS1.HANS.HOSTEUROPE.DE and ping fails:
ping: unknown host forum.opennauticalchart.org
ping: unknown host wiki.opennauticalchart.org

**Comment by OlafHannemann** [comment]
@leo12305 can you please check Dirk's question.

**Comment by leo12305** [comment]
Hallo Dirk,

ich kann leider nicht ins Forum sehen keine Rechte??

LG
Rolf

Am 11.12.2015 um 10:08 schrieb Dirk--:

**Comment by Dirk--** [comment]
Hi Rolf, 
the only issue: SSL-Cert is self signed and your browser might report a security warning. Just add exception and proceed....
